[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.zip", "php82Extensions.curl", "php82Extensions.xml", "nodejs"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["mkdir -p data/cache data/logs data/upload", "chmod -R 755 data"]

[start]
cmd = "php -S 0.0.0.0:$PORT"